# We put everything on one line, but use \n to create the break
format = """$username$hostname$directory$git_branch$python${fill}$time
$character"""

# Empty this out so it doesn't conflict
right_format = """"""

[fill]
symbol = " " # This creates invisible space to push the time to the right

[username]
show_always = false
style_user = "bold blue"
format = "[$user]($style) "



[hostname]
ssh_only = true
style = "bold green"
format = "on [$hostname]($style) "

[directory]
style = "bold cyan"
format = "in [$path]($style) "

[time]
disabled = false
time_format = "%R" # 24-hour clock (e.g. 23:01). Use "%I:%M %p" for 12-hour.
style = "bold yellow"
format = "at [$time]($style) "

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

